services:
  app:
    build: .
    container_name: trailblazer-backend
    restart: always
    ports:
      - "${PORT}:8080"
    environment:
      - ORIGIN=${ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_REDIRECT_URL=${TWITCH_REDIRECT_URL}
      - TWITCH_DEFAULT_BOT_ID=${TWITCH_DEFAULT_BOT_ID}
      - TWITCH_GQL_CLIENT_ID=${TWITCH_GQL_CLIENT_ID}
      - TWITCH_GQL_SHA256_HASH=${TWITCH_GQL_SHA256_HASH}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED}
      - NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED=${NEW_RELIC_APPLICATION_LOGGING_FORWARDING_MAX_SAMPLES_STORED}
    depends_on:
      - redis
    networks:
      - trailblazer-network
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --replica-read-only no
    volumes:
      - redis_data:/data
    networks:
      - trailblazer-network
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - trailblazer-network
volumes:
  redis_data:
    driver: local
networks:
  trailblazer-network:
    driver: bridge
