services:
  app:
    build: .
    container_name: trailblazer-backend
    restart: always
    ports:
      - "${PORT}:8080"
    environment:
      - ORIGIN=${ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_REDIRECT_URL=${TWITCH_REDIRECT_URL}
      - TWITCH_DEFAULT_BOT_ID=${TWITCH_DEFAULT_BOT_ID}
      - S3_REGION=${S3_REGION}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - NEW_RELIC_APP_NAME=${NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}